name: vnr_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.5

  # Geolocation & geocoding
  geolocator: ^11.1.0
  geocoding: ^2.1.3

  # Local storage
  sqflite: ^2.3.3
  path: ^1.9.1
  intl: ^0.18.1

  # Map
  flutter_map: ^6.2.1
  latlong2:

  #  flutter_map_location_marker: ^8.0.6

  # Connectivity & file export
  connectivity_plus: ^6.0.3
  share_plus: ^10.0.0
  path_provider: ^2.1.2
  csv: ^5.0.2
  open_file:
  permission_handler: ^12.0.1
  media_store_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
