name: vnr_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.5

  # compatible versions
  geolocator: ^11.1.0
  geocoding: ^2.1.3

  sqflite: ^2.3.3
  path: ^1.9.1
  intl: ^0.18.1

  # Newest stable flutter_map that supports Flutter 3.24
  flutter_map: ^6.1.0

  # plugin to show current location marker on map
  flutter_map_location_marker: ^8.0.6

  # REMOVE latlong2
  # REMOVE positioned_tap_detector_2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
